### Python program to a Sort Matrix by index-value equality count

In [2]:
def get_idx_ele_count(row):
    return len([ele for i,ele in enumerate(row) if ele == i])
test_list = [[3, 1, 2, 5, 4], [0, 1, 2, 3, 4], 
             [6, 5, 4, 3, 2], [0, 5, 4, 2]]
print("original list is:",test_list)
test_list.sort(key = get_idx_ele_count)
print("Sorted list:",test_list)

original list is: [[3, 1, 2, 5, 4], [0, 1, 2, 3, 4], [6, 5, 4, 3, 2], [0, 5, 4, 2]]
Sorted list: [[6, 5, 4, 3, 2], [0, 5, 4, 2], [3, 1, 2, 5, 4], [0, 1, 2, 3, 4]]


In [3]:
test_list = [[3, 1, 2, 5, 4], [0, 1, 2, 3, 4], 
             [6, 5, 4, 3, 2], [0, 5, 4, 2]]
print("original list is:",test_list)
result = sorted(test_list,key=lambda row:len([val for idx,val in enumerate(row) if val == idx]))
print("Sorted List is:",result)

original list is: [[3, 1, 2, 5, 4], [0, 1, 2, 3, 4], [6, 5, 4, 3, 2], [0, 5, 4, 2]]
Sorted List is: [[6, 5, 4, 3, 2], [0, 5, 4, 2], [3, 1, 2, 5, 4], [0, 1, 2, 3, 4]]


### Python Program to Reverse Every Kth row in a Matrix

In [7]:
test_list = [[5, 3, 2], [8, 6, 3], [3, 5, 2],
             [3, 6], [3, 7, 4], [2, 9]]
print("original list is:",test_list)
K = 3
result = []
for idx,val in enumerate(test_list):
    if (idx + 1)%K == 0:
        result.append(list(reversed(val)))
    else:
        result.append(val)
print("After reversing every Kth row:",result)

original list is: [[5, 3, 2], [8, 6, 3], [3, 5, 2], [3, 6], [3, 7, 4], [2, 9]]
After reversing every Kth row: [[2, 3, 5], [8, 6, 3], [3, 5, 2], [6, 3], [3, 7, 4], [2, 9]]


In [9]:
test_list = [[5, 3, 2], [8, 6, 3], [3, 5, 2],
             [3, 6], [3, 7, 4], [2, 9]]
print("original list is:",test_list)
K = 3
result = [val[::-1] if (idx + 1)%K==0 else val for idx,val in enumerate(test_list)]
print("After reversing every Kth row:",result)

original list is: [[5, 3, 2], [8, 6, 3], [3, 5, 2], [3, 6], [3, 7, 4], [2, 9]]
After reversing every Kth row: [[5, 3, 2], [8, 6, 3], [2, 5, 3], [3, 6], [3, 7, 4], [9, 2]]


In [10]:
test_list = [[5, 3, 2], [8, 6, 3], [3, 5, 2],
             [3, 6], [3, 7, 4], [2, 9]]
print("original list is:",test_list)
K = 3
result = []
for i in test_list:
    if (test_list.index(i)== K - 1):
        i.reverse()
        result.append(i)
    else:
        result.append(i)
print("After reversing every Kth row:",result)

original list is: [[5, 3, 2], [8, 6, 3], [3, 5, 2], [3, 6], [3, 7, 4], [2, 9]]
After reversing every Kth row: [[5, 3, 2], [8, 6, 3], [2, 5, 3], [3, 6], [3, 7, 4], [2, 9]]


In [28]:
test_list = [[5, 3, 2], [8, 6, 3], [3, 5, 2],
             [3, 6], [3, 7, 4], [2, 9]]
print("original list is:",test_list)
K = 3
for i in range(K-1,len(test_list),K):
    test_list[i] = test_list[i][::-1]
print("After reversing every Kth row:",test_list)

original list is: [[5, 3, 2], [8, 6, 3], [3, 5, 2], [3, 6], [3, 7, 4], [2, 9]]
After reversing every Kth row: [[5, 3, 2], [8, 6, 3], [2, 5, 3], [3, 6], [3, 7, 4], [9, 2]]


### Python Program to Convert String Matrix Representation to Matrix

In [31]:
import re
test_str = "[gfg,is],[best,for],[all,geeks]"
pattern = r"\[(.+?)\]"
result = re.findall(pattern,test_str)
result = [ele.split(",") for ele in result]
print("Original string is:",test_str)
print("Resultent Matrix:",result)

Original string is: [gfg,is],[best,for],[all,geeks]
Resultent Matrix: [['gfg', 'is'], ['best', 'for'], ['all', 'geeks']]


In [33]:
import json
test_str = '[["gfg", "is"], ["best", "for"], ["all", "geeks"]]'
print("Original string is:",test_str)
result = json.loads(test_str)
print("Resultent Matrix:",result)

Original string is: [["gfg", "is"], ["best", "for"], ["all", "geeks"]]
Resultent Matrix: [['gfg', 'is'], ['best', 'for'], ['all', 'geeks']]


In [37]:
test_str = "[gfg,is],[best,for],[all,geeks]"
print("Original string is:",test_str)
rows = test_str[1:-1].split("],[")
result = [ele.split(",") for ele in rows]
print("Resultent Matrix:",result)

Original string is: [gfg,is],[best,for],[all,geeks]
Resultent Matrix: [['gfg', 'is'], ['best', 'for'], ['all', 'geeks']]


In [39]:
import re
test_str = "[gfg,is],[best,for],[all,geeks]"
print("Original string is:",test_str)
pattern = r'\[([^]]+)\]'
result = re.findall(pattern,test_str)
result = [sub.split(",") for sub in result]
print("Resultent Matrix:",result)

Original string is: [gfg,is],[best,for],[all,geeks]
Resultent Matrix: [['gfg', 'is'], ['best', 'for'], ['all', 'geeks']]


### Count the frequency of matrix row length

In [40]:
test_list = [[6, 3, 1], [8, 9], [2],
             [10, 12, 7], [4, 11]]
print("The Original list is:",test_list)
result = dict()
for sub in test_list:
    if len(sub) not in result:
        result[len(sub)] = 1
    else:
        result[len(sub)] += 1
print("row length frequency is :",result)

The Original list is: [[6, 3, 1], [8, 9], [2], [10, 12, 7], [4, 11]]
row length frequency is : {3: 2, 2: 2, 1: 1}


In [41]:
from collections import Counter
test_list = [[6, 3, 1], [8, 9], [2],
             [10, 12, 7], [4, 11]]
print("The Original list is:",test_list)
result = dict(Counter(map(len,test_list)))
print("row length frequency is :",result)

The Original list is: [[6, 3, 1], [8, 9], [2], [10, 12, 7], [4, 11]]
row length frequency is : {3: 2, 2: 2, 1: 1}


In [44]:
l = dict(Counter(map(len,test_list)))
l

{3: 2, 2: 2, 1: 1}

In [46]:
test_list = [[6, 3, 1], [8, 9], [2],
             [10, 12, 7], [4, 11]]
print("The Original list is:",test_list)
result = dict()
x = []
for sub in test_list:
    x.append(len(sub))
y = set(x)
for i in y:
    result[i] = x.count(i)
print("row length frequency is :",result)

The Original list is: [[6, 3, 1], [8, 9], [2], [10, 12, 7], [4, 11]]
row length frequency is : {1: 1, 2: 2, 3: 2}


### Convert Integer Matrix to String Matrix

In [49]:
test_list = [[4, 5, 7], [10, 8, 3], [19, 4, 6], [9, 3, 6]]
print("The original list : " + str(test_list))
result = [[str(ele) for ele in lst] for lst in test_list]
print("The Data type converted matrix:",result)

The original list : [[4, 5, 7], [10, 8, 3], [19, 4, 6], [9, 3, 6]]
The Data type converted matrix: [['4', '5', '7'], ['10', '8', '3'], ['19', '4', '6'], ['9', '3', '6']]


In [50]:
test_list = [[4, 5, 7], [10, 8, 3], [19, 4, 6], [9, 3, 6]]
print("The original list : " + str(test_list))
result = [list(map(str,sub)) for sub in test_list]
print("The Data type converted matrix:",result)

The original list : [[4, 5, 7], [10, 8, 3], [19, 4, 6], [9, 3, 6]]
The Data type converted matrix: [['4', '5', '7'], ['10', '8', '3'], ['19', '4', '6'], ['9', '3', '6']]


In [53]:
import numpy as np
test_list = [[4, 5, 7], [10, 8, 3], [19, 4, 6], [9, 3, 6]]
print("The original list : " + str(test_list))
matrix = np.array(test_list)
print(matrix)
result = np.char.mod("%s",matrix).tolist()
print("The Data type converted matrix:",result)

The original list : [[4, 5, 7], [10, 8, 3], [19, 4, 6], [9, 3, 6]]
[[ 4  5  7]
 [10  8  3]
 [19  4  6]
 [ 9  3  6]]
The Data type converted matrix: [['4', '5', '7'], ['10', '8', '3'], ['19', '4', '6'], ['9', '3', '6']]


### Python Program to Convert Tuple Matrix to Tuple List

In [57]:
test_list = [[(4, 5), (7, 8)], [(10, 13), (18, 17)], [(0, 4), (10, 1)]]
print("The original list : " + str(test_list))
result = [ele for lst in test_list for ele in lst]
result = list(zip(*result))
print("The converted tuple list is:",result)

The original list : [[(4, 5), (7, 8)], [(10, 13), (18, 17)], [(0, 4), (10, 1)]]
The converted tuple list is: [(4, 7, 10, 18, 0, 10), (5, 8, 13, 17, 4, 1)]


In [59]:
from itertools import chain
test_list = [[(4, 5), (7, 8)], [(10, 13), (18, 17)], [(0, 4), (10, 1)]]
print("The original list : " + str(test_list))
result = list(zip(*chain.from_iterable(test_list)))
print("The converted tuple list is:",result)

The original list : [[(4, 5), (7, 8)], [(10, 13), (18, 17)], [(0, 4), (10, 1)]]
The converted tuple list is: [(4, 7, 10, 18, 0, 10), (5, 8, 13, 17, 4, 1)]


In [61]:
test_list = [[(4, 5), (7, 8)], [(10, 13), (18, 17)], [(0, 4), (10, 1)]]
print("The original list : " + str(test_list))
x = []
for i in test_list:
    for j in i:
        j = list(j)
        x.extend(j)
re1=[]
re2=[]
for i in range(0,len(x)):
    if (i%2==0):
        re1.append(x[i])
    else:
        re2.append(x[i])
result = []
result.append(tuple(re1))
result.append(tuple(re2))
print("The Converted tuple list is:",result)

The original list : [[(4, 5), (7, 8)], [(10, 13), (18, 17)], [(0, 4), (10, 1)]]
The Converted tuple list is: [(4, 7, 10, 18, 0, 10), (5, 8, 13, 17, 4, 1)]


In [63]:
matrix = ((1, 2, 3), (4, 5, 6), (7, 8, 9))
print("The original list : ",matrix)
result = tuple(map(lambda x:list(x),matrix))
print(result)

The original list :  ((1, 2, 3), (4, 5, 6), (7, 8, 9))
([1, 2, 3], [4, 5, 6], [7, 8, 9])


In [72]:
import numpy as np
test_list = [[(4, 5), (7, 8)], [(10, 13), (18, 17)], [(0, 4), (10, 1)]]
print("The original list : " + str(test_list))
array = np.array([ele for sub in test_list for ele in sub],np.int64)
result = tuple(map(tuple,array.T))
print("The Converted tuple list is:",result)

The original list : [[(4, 5), (7, 8)], [(10, 13), (18, 17)], [(0, 4), (10, 1)]]
The Converted tuple list is: ((4, 7, 10, 18, 0, 10), (5, 8, 13, 17, 4, 1))


In [75]:
def flatten(lst):
    if isinstance(lst,list):
        return [ele for sub in lst for ele in sub]
    else:
        return [lst]
test_list = [[(4, 5), (7, 8)], [(10, 13), (18, 17)], [(0, 4), (10, 1)]]
print("The original list : " + str(test_list))
result = flatten(test_list)
result = list(zip(*result))
print("The Converted tuple list is:",result)

The original list : [[(4, 5), (7, 8)], [(10, 13), (18, 17)], [(0, 4), (10, 1)]]
The Converted tuple list is: [(4, 7, 10, 18, 0, 10), (5, 8, 13, 17, 4, 1)]


### Group Elements in Matrix

In [1]:
test_list = [[5, 8], [2, 0], [5, 4], [2, 3], [7, 9]]
print("Original list:",test_list)
result = {idx[0]: [] for idx in test_list}
for idx in test_list:
    result[idx[0]].append(idx[1])
print("The Grouped matrix:",result)

Original list: [[5, 8], [2, 0], [5, 4], [2, 3], [7, 9]]
The Grouped matrix: {5: [8, 4], 2: [0, 3], 7: [9]}


In [12]:
from collections import defaultdict
test_list = [[5, 8], [2, 0], [5, 4], [2, 3], [7, 9]]
print("Original list:",test_list)
result = defaultdict(list)
for idx in test_list:
    result[idx[0]].append(idx[1])
print(result)

Original list: [[5, 8], [2, 0], [5, 4], [2, 3], [7, 9]]
defaultdict(<class 'list'>, {5: [8, 4], 2: [0, 3], 7: [9]})


In [13]:
test_list = [[5, 8], [2, 0], [5, 4], [2, 3], [7, 9]]
print("Original list:",test_list)
result = dict()
x = []
for i in test_list:
    if i[0] not in x:
        x.append(i[0])
for i in x:
    v=[]
    for j in test_list:
        if j[0]==i:
            v.append(j[1])
    result[i] = v
print("The Grouped Matrix:",result)

Original list: [[5, 8], [2, 0], [5, 4], [2, 3], [7, 9]]
The Grouped Matrix: {5: [8, 4], 2: [0, 3], 7: [9]}


In [16]:
from itertools import groupby
test_list = [[5, 8], [2, 0], [5, 4], [2, 3], [7, 9]]
print("Original list:",test_list)
test_list.sort()
groups = groupby(test_list,lambda x:x[0])
result = { k:[v[1] for v in group] for k,group in groups}
print("The Grouped Matrix:",result)

Original list: [[5, 8], [2, 0], [5, 4], [2, 3], [7, 9]]
The Grouped Matrix: {2: [0, 3], 5: [4, 8], 7: [9]}


### Assigning Subsequent Rows to Matrix first row elements

In [17]:
test_list = [[5, 8, 9], [2, 0, 9], [5, 4, 2], [2, 3, 9]]
print("Original list:",test_list)
result = {test_list[0][ele]:test_list[ele +1] for ele in range(len(test_list) - 1)}
print("The Assigned matrix is:",result)

Original list: [[5, 8, 9], [2, 0, 9], [5, 4, 2], [2, 3, 9]]
The Assigned matrix is: {5: [2, 0, 9], 8: [5, 4, 2], 9: [2, 3, 9]}


In [18]:
test_list = [[5, 8, 9], [2, 0, 9], [5, 4, 2], [2, 3, 9]]
print("Original list:",test_list)
result = dict(zip(test_list[0],test_list[1:]))
print("The Assigned matrix is:",result)

Original list: [[5, 8, 9], [2, 0, 9], [5, 4, 2], [2, 3, 9]]
The Assigned matrix is: {5: [2, 0, 9], 8: [5, 4, 2], 9: [2, 3, 9]}


In [21]:
test_list = [[5, 8, 9], [2, 0, 9], [5, 4, 2], [2, 3, 9]]
print("Original list:",test_list)
a = test_list[0]
b = test_list[1:len(test_list)]
d=dict()
for i in range(0,len(a)):
    d[a[i]] = b[i]
print("The Assigned matrix is:",d)

Original list: [[5, 8, 9], [2, 0, 9], [5, 4, 2], [2, 3, 9]]
The Assigned matrix is: {5: [2, 0, 9], 8: [5, 4, 2], 9: [2, 3, 9]}


### Adding and Subtracting Matrices in Python

In [22]:
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([[4, 5], [6, 7]])
print("Printing elements of first matrix")
print(A)
print("Printing elements of second matrix")
print(B)
print("Addition Of Two matrix:")
print(np.add(A,B))

Printing elements of first matrix
[[1 2]
 [3 4]]
Printing elements of second matrix
[[4 5]
 [6 7]]
Addition Of Two matrix:
[[ 5  7]
 [ 9 11]]


In [23]:
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([[4, 5], [6, 7]])
print("Printing elements of first matrix")
print(A)
print("Printing elements of second matrix")
print(B)
print("Subtraction Of Two matrix:")
print(np.subtract(A,B))

Printing elements of first matrix
[[1 2]
 [3 4]]
Printing elements of second matrix
[[4 5]
 [6 7]]
Subtraction Of Two matrix:
[[-3 -3]
 [-3 -3]]


In [25]:
matrix1 = [[1, 2], [3, 4]]
matrix2 = [[4, 5], [6, 7]]
print("Printing element of first matrix:")
for raw in matrix1:
    for ele in raw:
        print(ele,end=" ")
    print()
    
print("Printing element of second matrix:")
for raw in matrix2:
    for ele in raw:
        print(ele,end=" ")
    print()
result = [[0,0],[0,0]]
for i in range(len(matrix1)):
    for j in range(len(matrix1[0])):
        result[i][j] = matrix1[i][j] - matrix2[i][j]
print("Subtraction of two matrix:")
for raw in result:
    for ele in raw:
        print(ele,end=" ")
    print()

Printing element of first matrix:
1 2 
3 4 
Printing element of second matrix:
4 5 
6 7 
Subtraction of two matrix:
-3 -3 
-3 -3 


### Convert Matrix to dictionary

In [26]:
test_list = [[5, 6, 7], [8, 3, 2], [8, 2, 1]] 
print("The Original list is:",test_list)
result = {idx +1:test_list[idx] for idx in range(len(test_list))}
print("The Constructed Dictionary:",result)

The Original list is: [[5, 6, 7], [8, 3, 2], [8, 2, 1]]
The Constructed Dictionary: {1: [5, 6, 7], 2: [8, 3, 2], 3: [8, 2, 1]}


In [28]:
test_list = [[5, 6, 7], [8, 3, 2], [8, 2, 1]] 
print("The Original list is:",test_list)
result = {idx:val for idx,val in enumerate(test_list,start=1)}
print("The Constructed Dictionary:",result)

The Original list is: [[5, 6, 7], [8, 3, 2], [8, 2, 1]]
The Constructed Dictionary: {1: [5, 6, 7], 2: [8, 3, 2], 3: [8, 2, 1]}


### Convert Matrix to Custom Tuple Matrix

In [30]:
test_list = [[4, 5, 6], [6, 7, 3], [1, 3, 4]]
print("The Original list is:",test_list)
add_list = ['Gfg', 'is', 'best']
result = []
for idx,ele in zip(add_list,test_list):
    for val in ele:
        result.append((idx,val))
        
print("Matrix after conversion:",result)

The Original list is: [[4, 5, 6], [6, 7, 3], [1, 3, 4]]
Matrix after conversion: [('Gfg', 4), ('Gfg', 5), ('Gfg', 6), ('is', 6), ('is', 7), ('is', 3), ('best', 1), ('best', 3), ('best', 4)]


In [31]:
test_list = [[4, 5, 6], [6, 7, 3], [1, 3, 4]]
print("The Original list is:",test_list)
add_list = ['Gfg', 'is', 'best']
result = [(ele1,ele2) for ele1,sub in zip(add_list,test_list) for ele2 in sub]
        
print("Matrix after conversion:",result)

The Original list is: [[4, 5, 6], [6, 7, 3], [1, 3, 4]]
Matrix after conversion: [('Gfg', 4), ('Gfg', 5), ('Gfg', 6), ('is', 6), ('is', 7), ('is', 3), ('best', 1), ('best', 3), ('best', 4)]


In [33]:
test_list = [[4, 5, 6], [6, 7, 3], [1, 3, 4]]
print("The Original list is:",test_list)
add_list = ['Gfg', 'is', 'best']
result = []
for i in range(0,len(add_list)):
    for j in range(0,len(test_list)):
        result.append((add_list[i],test_list[i][j]))
        
print("Matrix after conversion:",result)

The Original list is: [[4, 5, 6], [6, 7, 3], [1, 3, 4]]
Matrix after conversion: [('Gfg', 4), ('Gfg', 5), ('Gfg', 6), ('is', 6), ('is', 7), ('is', 3), ('best', 1), ('best', 3), ('best', 4)]


### Matrix Row subset

In [34]:
test_list = [[4, 5, 7], [2, 3, 4], [9, 8, 0]]
print("The Original list is:",test_list)
check_matr = [[2, 3], [1, 2], [9, 0]]
result = [ele for ele in check_matr if any(all(a in sub for a in ele) for sub in test_list)]
print("Matrix row subset:",result)

The Original list is: [[4, 5, 7], [2, 3, 4], [9, 8, 0]]
Matrix row subset: [[2, 3], [9, 0]]


In [35]:
from itertools import product
test_list = [[4, 5, 7], [2, 3, 4], [9, 8, 0]]
print("The Original list is:",test_list)
check_matr = [[2, 3], [1, 2], [9, 0]]
result = [a for a,b in product(check_matr,test_list) if set(a) <= set(b)]
print("Matrix row subset:",result)

The Original list is: [[4, 5, 7], [2, 3, 4], [9, 8, 0]]
Matrix row subset: [[2, 3], [9, 0]]


In [36]:
test_list = [[4, 5, 7], [2, 3, 4], [9, 8, 0]]
print("The Original list is:",test_list)
check_matr = [[2, 3], [1, 2], [9, 0]]
result = []
for row in check_matr:
    for lst in test_list:
        if set(row).issubset(set(lst)):
            result.append(row)
print("Matrix row subset:",result)

The Original list is: [[4, 5, 7], [2, 3, 4], [9, 8, 0]]
Matrix row subset: [[2, 3], [9, 0]]


In [38]:
test_list = [[4, 5, 7], [2, 3, 4], [9, 8, 0]]
check_matr = [[2, 3], [1, 2], [9, 0]]
def is_subset(a,b):
    return set(a).issubset(set(b))
result = [list(a) for a in check_matr if any(map(lambda b:is_subset(a,b),test_list))]
print("Matrix row subset:",result)

Matrix row subset: [[2, 3], [9, 0]]


### Group similar elements into Matrix

In [39]:
from itertools import groupby
test_list = [1, 3, 5, 1, 3, 2, 5, 4, 2]
print("The Original list is:",test_list)
result = [list(val) for key,val in groupby(sorted(test_list))]
print("Matrix After grouping:",result)

The Original list is: [1, 3, 5, 1, 3, 2, 5, 4, 2]
Matrix After grouping: [[1, 1], [2, 2], [3, 3], [4], [5, 5]]


In [45]:
from collections import Counter
test_list = [1, 3, 5, 1, 3, 2, 5, 4, 2]
print("The Original list:",test_list)
temp = Counter(sorted(test_list))
result = [[key]*val for key,val in temp.items()]
print("Matrix after grouping:",result)

The Original list: [1, 3, 5, 1, 3, 2, 5, 4, 2]
Matrix after grouping: [[1, 1], [2, 2], [3, 3], [4], [5, 5]]


In [46]:
from collections import defaultdict
test_list = [1, 3, 5, 1, 3, 2, 5, 4, 2]
print("The Original list:",test_list)
d = defaultdict(list)
for ele in test_list:
    d[ele].append(ele)
result = list(d.values())
print("Matrix after grouping:",result)

The Original list: [1, 3, 5, 1, 3, 2, 5, 4, 2]
Matrix after grouping: [[1, 1], [3, 3], [5, 5], [2, 2], [4]]


In [48]:
test_list = [1, 3, 5, 1, 3, 2, 5, 4, 2]
group_dict = {}
for ele in test_list:
    if ele not in group_dict:
        group_dict[ele] = [ele]
    else:
        group_dict[ele].append(ele)
result = list(group_dict.values())
print("Matrix after grouping:",result)

Matrix after grouping: [[1, 1], [3, 3], [5, 5], [2, 2], [4]]


In [50]:
test_list = [1, 3, 5, 1, 3, 2, 5, 4, 2]
grouped = []
unique = set(test_list)
for ele in unique:
    sublist = [x for x in test_list if x == ele]
    grouped.append(sublist)
    
print("Matrix after grouping:",grouped)

Matrix after grouping: [[1, 1], [2, 2], [3, 3], [4], [5, 5]]


### Row-wise element Addition in Tuple Matrix

In [53]:
test_list = [[('Gfg', 3), ('is', 3)], [('best', 1)], [('for', 5), ('geeks', 1)]]
print("The original list is : " + str(test_list))
cus_ele = [6, 7, 8]
result = [[sub + (cus_ele[idx],) for sub in val] for idx,val in enumerate(test_list)]
print("Matrix after raw element addition :",result)

The original list is : [[('Gfg', 3), ('is', 3)], [('best', 1)], [('for', 5), ('geeks', 1)]]
Matrix after raw element addition : [[('Gfg', 3, 6), ('is', 3, 6)], [('best', 1, 7)], [('for', 5, 8), ('geeks', 1, 8)]]


In [54]:
test_list = [[('Gfg', 3), ('is', 3)], [('best', 1)], [('for', 5), ('geeks', 1)]]
print("The original list is : " + str(test_list))
cus_ele = [6, 7, 8]
result = [[(idx,val) for idx in key] for key,val in zip(test_list,cus_ele)]
print("Matrix after raw element addition :",result)

The original list is : [[('Gfg', 3), ('is', 3)], [('best', 1)], [('for', 5), ('geeks', 1)]]
Matrix after raw element addition : [[(('Gfg', 3), 6), (('is', 3), 6)], [(('best', 1), 7)], [(('for', 5), 8), (('geeks', 1), 8)]]


In [55]:
test_list = [[('Gfg', 3), ('is', 3)], [('best', 1)], [('for', 5), ('geeks', 1)]]
print("The original list is : " + str(test_list))
cus_ele = [6, 7, 8]
result = []
for idx,row in enumerate(test_list):
    result.append(list(map(lambda x:x+(cus_ele[idx],),row)))
print("Matrix after raw element addition :",result)

The original list is : [[('Gfg', 3), ('is', 3)], [('best', 1)], [('for', 5), ('geeks', 1)]]
Matrix after raw element addition : [[('Gfg', 3, 6), ('is', 3, 6)], [('best', 1, 7)], [('for', 5, 8), ('geeks', 1, 8)]]


### Create an n x n square matrix, where all the sub-matrix have the sum of opposite corner elements as even

In [57]:
from itertools import count
def sub_mat_even(n):
    temp = count(1)
    lst = [[next(temp) for i in range(n)] for i in range(n)]
    print(lst)
    if n%2==0:
        for i in range(0,len(lst)):
            if i%2 == 1:
                lst[i][:] = lst[i][::-1]
                
    for i in range(n):
        for j in range(n):
            print(lst[i][j],end=" ")
        print()
n = 4
sub_mat_even(n)
            

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]
1 2 3 4 
8 7 6 5 
9 10 11 12 
16 15 14 13 
